services:
  jellyseerr:
    image: ghcr.nju.edu.cn/seerr-team/seerr:latest
    container_name: jellyseerr
    restart: unless-stopped

    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - PORT=5055
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/app/config
    networks:
      family-network:
        ipv4_address: ${JELLYSEERR_IP}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

networks:
  family-network:
    external: true
