services:
  jellyseerr:
    image: ghcr.nju.edu.cn/seerr-team/seerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    depends_on:
      sonarr:
        condition: service_healthy
      radarr:
        condition: service_healthy
      jellyfin:
        condition: service_healthy

    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - PORT=5055
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - "${JELLYSEERR_PORT:-5055}:5055"
    volumes:
      - ${DATA_DIR:-/srv/media}/config/jellyseerr:/app/config
    networks:
      - family-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

networks:
  family-network:
    external: true
