services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped

    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - PUID=0
      - PGID=0
    volumes:
      - ./config:/config
    networks:
      family-network:
        ipv4_address: ${PROWLARR_IP}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  family-network:
    external: true
